### PR TITLE
changing defaults

### PR DESCRIPTION
**Pull request by pawelkaczmarekuk**
### Change description ###

I moved the init of ActionEvents to media-viewer. It should be an optional action if a consumer chooses not to use the toolbar.

### CODE REVIEW

**Comment by linusnorton** [comment]
So it can still be set if required?

**Comment by pawelkaczmarekuk** [comment]
> So it can still be set if required?

yes.

**Comment by linusnorton** [comment]
Could you update the README.md to state that it is now optional

**Comment by pawelkaczmarekuk** [comment]
> Could you update the README.md to state that it is now optional

Done.

**Pull request merged**
